apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ci-namespaces.fabrique.social.gouv.fr
spec:
  group: fabrique.social.gouv.fr
  names:
    kind: CiNamespace
    plural: ci-namespaces
    singular: ci-namespace
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
     status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              startupRef:
                type: string
              clusterRef:
                type: string