apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: startups.fabrique.social.gouv.fr
spec:
  group: fabrique.social.gouv.fr
  names:
    kind: Startup
    plural: startups
    singular: startup
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}